# Generated by Django 4.2.2 on 2023-06-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmodel',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dynamicmodel',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
