# Generated by Django 4.2.2 on 2023-06-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dynamicmodel_fields_alter_dynamicmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicmodel',
            old_name='title',
            new_name='name',
        ),
    ]
